import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Script from "next/script";
// import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yusuf Ansari",
  description: "A Front End Web Developer Portfolio Created using Next.js, Typscript & Tailwind CSS",
  keywords: [
    "Yusuf Ansari",
    "Front End Web Developer",
    "Best Front End Web Developer",
    "Next.js",
    "TypeScript",
    "Tailwind CSS",
    "Portfolio",
  ],
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Google tag (gtag.js) */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-WBB7TWYR8D"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-WBB7TWYR8D', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
      {/* JSON-LD markup generated by Google Structured Data Markup Helper. */}
      <Script
          id="structured-data"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "http://schema.org",
              "@type": "Article",
              "name": "Yusuf Ansari",
              "author": {
                "@type": "Person",
                "name": "Yusuf"
              },
              "image": "https://yusuf0786.github.io/portfolio/img/myimg.png",
              "articleSection": "https://yusuf0786.github.io/portfolio/services/index.html",
              "articleBody": "https://yusuf0786.github.io/portfolio/services/index.html#",
              "url": "https://yusufansari.infinityfreeapp.com/index.html",
              "publisher": {
                "@type": "Organization",
                "name": "Yusuf Ansari"
              }
            }),
          }}
        />
        <link rel="canonical" href="https://yusuf0786.github.io/mywebsite/" />
        <meta name="google-site-verification" content="BhJrHvP820i8RZ3nEKPnvulfJ26NSopHTu8_Jw0u-Vs" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
          {children}
          <div id="modal-root"/>
        <Footer/>
      </body>
    </html>
  );
}
